version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./api
    container_name: pizarra_api
    restart: always
    depends_on:
      - postgres
      - mongo
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

volumes:
  postgres_data:
  mongo_data:
